### PR TITLE
Change white to blue backgrounds

### PR DESCRIPTION
**Pull request by Maks-s**
Change all white backgrounds to a more eye-friendly blue

# Screenshots
### Main page
Screenshot_2019-03-10 Encryptic

### About
Screenshot_2019-03-10 Encryptic(1)

### CODE REVIEW

**Comment by Prune2000** [comment]
I'm not 100% if I'm sold on the color. One minute I love it with a retro feel to it, and the minute later I think it's too much. Maybe we could try other colors to see?

Really like it on the about page though.

By the way, I don't understand why the texts in the header and the first section are so small. There is a media query activated for screens above 1900px width. Could you have a look at it with your screen size please?

**Comment by Maks-s** [comment]
I see, I'm not really an expert on colors though, any idea of what we can use ? I like the first section being blue, as it's the color associated with Encryptic

I have a 1080p (1920x1080) screen with the task bar on the left so it's down to 1840px which is smaller than 1903px.
Also, I prefer by far the small text over the **HUGE** text, the word 'application' is literally the same size as my hand 😸

**Comment by Prune2000** [comment]
Haha understood. I'll make some changes to the wide screen styling then :)

Yeah the blue in the header probably works. But I feel like for the section with the gifs, it's too much of a contrast with the black. So maybe leaving this one white and just the header + about page blue?

**Comment by Maks-s** [comment]
Sure ! The page looks like this now : 
Screenshot_2019-03-10 Encryptic

I'm waiting for your approval to commit 😉

**Comment by Prune2000** [comment]
I think it works well now! The gifs being from the dark theme and taking enough space, I feel like this section is not a problem in white, but looking at the current header, it feels more empty than your version with the blue.

If you agree, let's merge it?

**Comment by Maks-s** [comment]
Ok 😄

**Pull request merged**
